# Generated by Django 4.2.7 on 2023-12-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.FileField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='media/avatars'),
        ),
    ]
