# Generated by Django 4.2.7 on 2023-12-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_profile_description_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.FileField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='media/'),
        ),
    ]
