# Generated by Django 4.2.7 on 2023-12-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.FileField(blank=True, default='default_avatar.png', null=True, upload_to=''),
        ),
    ]
